manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: paulshir
      url-base: https://github.com/paulshir
  projects:
    - name: zmk
      # remote: zmkfirmware
      # revision: main
      remote: paulshir
      revision: main+pio-led
      # revision: paulshir
      # revision: split-serial-pr+pio-led
      import: app/west.yml
  self:
    path: config
